---
author: "Nelson Simões - CTI/Planserv"
date: "23 de agosto de 2017"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    highlight: pygments
---

# Avaliação do crescimento da conta (Volume x Valor)

---

### Preparação do ambiente

Bibliotecas utilizadas no trabalho no código abaixo
```{r setup, include=TRUE, message=FALSE, warning=FALSE}
## Opções iniciais de configuração do ambiente
# ------------------------------------------------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
# ------------------------------------------------------------------------------------------
library("stringr", lib.loc="~/R/win-library/3.4")
library("dplyr", lib.loc="~/R/win-library/3.4")
library("ggplot2", lib.loc="~/R/win-library/3.4")
library("readr", lib.loc="~/R/win-library/3.4")
library("tibble", lib.loc="~/R/win-library/3.4")
library("tidyr", lib.loc="~/R/win-library/3.4")
library("magrittr", lib.loc="~/R/win-library/3.4")
library("readxl", lib.loc="~/R/win-library/3.4")
library("purrr", lib.loc="~/R/win-library/3.4")
library("DBI", lib.loc="~/R/win-library/3.4")
library("ROracle", lib.loc="~/R/win-library/3.4")
# ------------------------------------------------------------------------------------------
```

```{r conn, include=FALSE}
drv <- dbDriver("Oracle")
con <- dbConnect(drv, "ts_consulta", "ts_consulta", dbname='TS.INTRANET')
```

### Criação de base a partir do banco de dados

```{sql connection=con, eval=FALSE, include=FALSE, output.var="x_vv_main"}
select  substr(fc.ID_TEMPO_MES_ANO_REF,1,4) ano,
        substr(fc.ID_TEMPO_MES_ANO_REF,1,6) anomes,
        sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0))  VT,        
        round((sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)))/(tbt.BT),2) VM,
        round((sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)))/(count(distinct fc.COD_TS)),2) VA,
        round((sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)))/(count(distinct fc.CONTA)),2) VC,
        round((sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)))/(count(1)),2) VI,
        sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0))  QP,        
        round((sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0)))/(tbt.BT),2) QM,        
        round((sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0)))/(count(distinct fc.COD_TS)),2) QA,
        round((sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0)))/(count(distinct fc.CONTA)),2) QC,
        round((sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0)))/(count(1)),2) QI,
        (sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)))/(sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0))) VQ,
        tbt.BT,
        count(distinct fc.COD_TS) BA,
        count(distinct fc.CONTA) CT,
        count(1) IT,
        count(distinct fc.COD_TS)/tbt.BT PA        
from    TS.FAT_ITEM_CONTA fc,
        (select  to_char(pcm.mes_ano_ref,'RRRRMM') anomes,
                sum(qtd_ativos) BT
        from    ts.posicao_cadastro_mes pcm           
        where   pcm.mes_ano_ref between to_date ('01/01/2014','dd/mm/yyyy') and to_date ('01/07/2017','dd/mm/yyyy') 
        group by   
                to_char(pcm.mes_ano_ref,'RRRRMM')
        order by 1) tbt
where   substr(fc.ID_TEMPO_MES_ANO_REF,1,6) = tbt.anomes
--and     substr(fc.ID_TEMPO_MES_ANO_REF,1,6) in ('201605')--, '201606', '201705', '201706')
group by substr(fc.ID_TEMPO_MES_ANO_REF,1,4),
         substr(fc.ID_TEMPO_MES_ANO_REF,1,6),
         tbt.BT
having  sum(nvl(fc.QTD_ITEM,0)) - sum(nvl(fc.QTD_GLOSADO,0)) > 0
or      sum(nvl(fc.VAL_APROVADO_ITEM,0)) + sum(nvl(fc.VALOR_PAGO_REVISAO,0)) > 0
order by 2
```

```{r importação}
## Importação, para processamento offline
# ------------------------------------------------------------------------------------------
x_vv_main <- read_excel('VV_extract_sqlbi_m18.xlsx') #'VV_extract_sqlbi_59m.xlsx''VV_extract_sqlbi.xls'

x_vv_main %<>% 
  mutate(ANOMES = factor(.$ANOMES), ANO = factor(.$ANO)) %>% 
  as.tibble()
```

### Processo de criação do sumário anual

```{r processo, message=FALSE, warning=FALSE}
## Quebra em blocos por ano, calcula a média de cada variável, armazena em lista de planilhas
# ------------------------------------------------------------------------------------------

mn.ano <- x_vv_main %>%
  split(.$ANO) %>%
  map(map_dbl, mean)

## Cria planilha vazia com nomes de colunas a partir de um bloco da lista acima
# ------------------------------------------------------------------------------------------

vv_ano <- setNames(data.frame(matrix(ncol = 17, nrow = 0)),
                   names(mn.ano[[1]])[-2]) %>% 
  as.tibble()

## Extrai variáveis dos blocos na lista para a planilha vazia
# ------------------------------------------------------------------------------------------

for (i in seq_along(mn.ano)) vv_ano[i, 1:17] <- c(ANO = names(mn.ano[i]),mn.ano[[i]][3:18])

## Converte variáveis para número de dupla precisão e ano para fator
# ------------------------------------------------------------------------------------------

vv_ano[,2:17] %<>% map_df(as.double)
vv_ano$ANO %<>% factor(.)

## Função para calculo de variação percentual em relação ao ano anterior
# ----------------------------------------------------------------------
## f.lag_perc <- function(col) (col-lag(col))/lag(col)

## Calcula a variação percentual ano a ano de cada variável
# ------------------------------------------------------------------------------------------

vv_var_perc_ano <- vv_ano[,2:17] %>%
  map_df(function(.) (.-lag(.))/lag(.)) %>%
  cbind(vv_ano[,1],.)

## Para retirada do ano sem valores prévios no resultado acima
# ------------------------------------------------------------------------------------------
## @2 #'['(2:dim(vv_ano)[1],) %>% 
## @3 #2:dim(vv_ano)[1]

## Renomeia colunas, para junção de planilhas
# ------------------------------------------------------------------------------------------

colnames(vv_var_perc_ano) <- paste0(colnames(vv_var_perc_ano),'.vp')
names(vv_var_perc_ano)[1] <- 'ANO'

## Junção de planilhas
# ------------------------------------------------------------------------------------------

vv_ano_n <- merge(vv_ano, vv_var_perc_ano, by = 'ANO')

## Reordenação de campos
# ------------------------------------------------------------------------------------------

names.v <- names(vv_ano)[1]

for (i in seq_along(names(vv_ano))) {
  if (i > 1) {
    names.v[length(names.v)+1] <- c(names(vv_ano)[i])
    names.v[length(names.v)+1] <- paste0(names(vv_ano)[i], '.vp')
  }
}

vv_ano_n <- select(vv_ano_n, names.v)


## Alternativa para reordenação
# ------------------------------------------------------------------------------------------
## vv_ano_n <- vv_ano_n[,c(1,2,18,3,19,4,20,5,21,6,22,7,23,8,24,9,25,
##                        10,26,11,27,12,28,13,29,14,30,15,31,16,32,17,33)]

## Exportação de planilha
# ------------------------------------------------------------------------------------------

write.csv2(vv_ano_n, 'resumo_ano.csv')

print(as.tibble(vv_ano_n))
```

### Escala de dados por Ano e Mês para análise gráfica no tempo

```{r escala anomes, message=FALSE, warning=FALSE}
## Geração de planilha com valores convertidos em escala de desvío padrão
# ------------------------------------------------------------------------------------------
vv_am_scale <- x_vv_main[3:18] %>% 
  map_df(scale, F, T)

## Renomeia colunas e união de planilhas
# ------------------------------------------------------------------------------------------
colnames(vv_am_scale) <- paste0(colnames(vv_am_scale),'.sd')

vv_am_scale <- cbind(x_vv_main[1:2], vv_am_scale)

vv_am_scale_n <- merge(x_vv_main, vv_am_scale, by = 'ANOMES')

colnames(vv_am_scale_n)[2] <- 'ANO'

## Reordenação de campos
# ------------------------------------------------------------------------------------------
names.v <- names(x_vv_main)[1]
names.v[2] <- names(x_vv_main)[2]

for (i in seq_along(names(x_vv_main))) {
  if (i > 2) {
    names.v[length(names.v)+1] <- c(names(x_vv_main)[i])
    names.v[length(names.v)+1] <- paste0(names(x_vv_main)[i], '.sd')
  }
}

vv_am_scale_n <- select(vv_am_scale_n, names.v)

## Exportação de planilha
# ------------------------------------------------------------------------------------------

write.csv2(vv_am_scale_n, 'resumo_anomes.csv')

print(as.tibble(vv_am_scale_n))
```

### Avaliação gráfica

```{r gráficos, fig.height=7, fig.width=10}
#names(vv_am_scale_n)

## Formatação da planilha para plotagem gráfica
# ------------------------------------------------------------------------------------------
vv_plot <- vv_am_scale_n %>%
  select(ANO, ANOMES, 
         'Quantidade Aprovada' = QP.sd,
         'Valor Total' = VT.sd, 
         #'Quantidade Média' = QM.sd, 
         #'Ticket Médio' = VM.sd, 
         #'Quantidade por Atendido' = QA.sd, 
         #'Valor por Atendido' = VA.sd, 
         #'Quantidade por Conta' = QC.sd, 
         #'Valor por Conta' = VC.sd, 
         #'Quantidade por Item' = QI.sd, 
         #'Valor por Item' = VI.sd,
         'Valor por Quantidade' = VQ.sd#,
         #'Beneficiários Totais' = BT.sd,
         #'Beneficiários Atendidos' = BA.sd,
         #'Quantidade de Contas' = CT.sd,
         #'Quantidade de Itens' = IT.sd,
         #'Percentual de Atendidos' = PA.sd
         ) %>% 
  gather(-ANO,
         -ANOMES,
         key = 'Indicador', value = 'Valor')

## Gráfico de dados padronizados
# ------------------------------------------------------------------------------------------
ggplot(data = vv_plot, aes(x = ANOMES)) +
  geom_line(aes(y = Valor, 
                group = Indicador,
                col = Indicador),
            size = 1.1) +
  labs(title = 'Comparação de Indicadores por dados padronizados',
       x = 'Ano e Mês',
       y = 'Desvios Padrão') +
  theme_dark() +
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 1,
                                   size = 9,
                                   hjust = 1))

## Gráfico a partir de planilha original
# ------------------------------------------------------------------------------------------
ggplot(data = vv_am_scale_n, aes(x = ANOMES)) +
  geom_bar(aes(y = QP.sd), 
           fill = 'orange', 
           width = 0.9, 
           alpha = 0.6, 
           stat = 'sum',
           show.legend = F) +
  geom_label(aes(x='201402', y=1.13), 
             label = 'Quantidade', col = 'orange', hjust = 'left') +  
  geom_bar(aes(y = VT.sd), 
           fill = 'blue', 
           width = 0.6, 
           alpha = 0.3, 
           stat = 'sum',
           show.legend = F) +
  geom_label(aes(x='201402', y=1.2), 
             label = 'Valor', col = 'blue', hjust = 'left') +
  labs(title = 'Comparação de Indicadores por dados padronizados',
       x = 'Ano e Mês',
       y = 'Desvios Padrão') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 1,
                                   size = 9,
                                   hjust = 1))

## Gráfico da diferença entre variação padronizada entre Valor e Quantidade, por ano
# ------------------------------------------------------------------------------------------
ggplot(data = vv_am_scale_n, aes(x = ANOMES)) +
  geom_line(aes(y = VT.sd-QP.sd), col = 'light blue', size = 1.1, group = 1) + #, col = ANO
  geom_line(aes(y = mean(VT.sd-QP.sd)), col = 'orange', size = 1.1, group = 1) +
  facet_wrap(~ANO, ncol = 2, scales = "free") +
  labs(title = 'Comparação de Indicadores por dados padronizados',
       x = 'Ano e Mês',
       y = 'Desvios Padrão') +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 1,
                                   size = 9,
                                   hjust = 1))

```

### Analise de faixa etária

```{sql connection=con, eval=FALSE, include=FALSE, output.var="x_vv_faixa"}
select  to_char(pcm.mes_ano_ref,'RRRRMM') anomes,
        fe.DESC_FAIXA faixa,
        sum(qtd_ativos) BT
from    ts.posicao_cadastro_mes pcm,
        TS.FAIXA_ETARIA fe
where   pcm.mes_ano_ref between to_date ('01/01/2014','dd/mm/yyyy') and to_date ('01/07/2017','dd/mm/yyyy') 
and     pcm.TIPO_FAIXA_ETARIA = fe.TIPO_FAIXA
and     pcm.COD_FAIXA_ETARIA = fe.COD_FAIXA_ETARIA
group by   
        to_char(pcm.mes_ano_ref,'RRRRMM'),
        fe.DESC_FAIXA
order by 1,2
```

### Gráficos e resumo

```{r faixa, fig.height=7, fig.width=10}
x_vv_faixa <- read_excel('beneficiarios_faixa.xlsx')

x_vv_faixa %<>% 
  mutate(ANO = factor(str_sub(ANOMES, 1, 4)), 
         ANOMES = factor(ANOMES), 
         FAIXA = factor(FAIXA, levels = c("até 18 anos", "19 a 23 anos", 
                                          "24 a 28 anos", "29 a 33 anos", 
                                          "34 a 38 anos", "39 a 43 anos", 
                                          "44 a 48 anos", "49 a 53 anos", 
                                          "54 a 58 anos", "59 anos ou mais"))) %>% 
  select(ANO, ANOMES, FAIXA, BENEFICIARIOS = BT)

vv_faixa_ano <- x_vv_faixa %>% 
  group_by(ANO, FAIXA) %>% 
  summarise(BENEFICIARIOS.md = mean(BENEFICIARIOS)) %>% 
  as.data.frame() %>% 
  mutate(TOTAL_B = vv_ano[match(.$ANO, vv_ano$ANO), 13][[1]]) %>% 
  mutate(P_FAIXA = round((BENEFICIARIOS.md/TOTAL_B)*100,3))

ggplot(data = vv_faixa_ano, aes(x = ANO)) +
  geom_bar(aes(y = BENEFICIARIOS.md, group = FAIXA, fill = FAIXA), 
           width = 0.9, alpha = 0.75, 
           stat = 'identity',
           position = 'fill') +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +
  scale_fill_brewer(palette = 'Spectral',
                    direction = 1) +
  labs(title = 'Percentual de faixa etária por ano',
       x = 'Ano', 
       y = 'Percentual') +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1, 
                                   size = 9, 
                                   hjust = 1))

ggplot(data = x_vv_faixa , aes(x = ANOMES)) +
  geom_line(aes(y = BENEFICIARIOS, color = FAIXA, group = FAIXA), 
            size = 1, alpha = 1, show.legend = T) +
  scale_y_continuous(breaks = seq(10000, 200000, by = 5000)) +
  scale_colour_manual(values = c('blue',
                                 'yellow',
                                 'green',
                                 'red',
                                 'orange',
                                 'dark green',
                                 'black',
                                 'gray',
                                 'violet',
                                 'light blue')) +
  labs(title = 'Evolução da faixa etária',
       x = 'Ano e mês', 
       y = 'Beneficiários') +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1, 
                                   size = 9, 
                                   hjust = 1))

f.stats <- function(vec) {
  res <- double()
  res[1] <- min(vec)
  res[2] <- max(vec)
  res[3] <- res[2]-res[1]
  res[4] <- sum(vec)
  res[5] <- round(res[3]/res[1]*100, 4)
  names(res) <- c('min', 'max', 'delta', 'sum', 'p_delta')
  return(res)
}

faixa_am.df <- x_vv_faixa %>% 
  split(.$FAIXA) %>% 
  map(arrange, ANOMES, FAIXA) %>% 
  map("BENEFICIARIOS") %>% 
  map(f.stats) %>% 
  map('delta') %>% 
  unlist() %>% 
  as.data.frame() %>% 
  cbind(rownames(.), .) %>% 
  as.tibble()

names(faixa_am.df) <- c('FAIXA','DELTA')

faixa_am.df
print(vv_faixa_ano)
```

